chore(Form): stabilize behavior
cube-js/cube-ui-kit pull request #112
Opened 2022-06-17 17:14 UTC by tenphi

### Form
- Fixes `rules` update
- Fixes `onSubmit`, `onSubmitFailed`, `onValuesChange` update
- Clear error on external `setFieldValue` with different value

### Other
- TooltipProvider: change `useEffect` behavior to avoid loop (I don't know exactly why)
- Update ReactAria/Select to avoid loop as well

2022-06-20 09:44 UTC, nikolaykost requested changes

2022-06-20 09:44 UTC, nikolaykost commented on src/components/forms/Form/Field.tsx
> +  if (field) {
Its really not working inside useEffect?

2022-06-20 09:44 UTC, nikolaykost commented on src/components/forms/Form/useForm.tsx
> +  setFieldValue(name: string, value: any, touched = false, skipRender = false) {
`any` -> `unknown` or generic?

2022-06-20 13:12 UTC, tenphi commented on src/components/forms/Form/useForm.tsx
> +  setFieldValue(name: string, value: any, touched = false, skipRender = false) {
It should be `any`.

2022-06-20 13:19 UTC, tenphi commented on src/components/forms/Form/Field.tsx
> +  if (field) {
It shouldn't be inside `useEffect`. It's a sync assignment.

2022-06-22 08:52 UTC, nikolaykost approved these changes

2022-06-22 10:53 UTC, merged