fix: whitewashing of Select component
cube-js/cube-ui-kit pull request #113
Opened 2022-06-20 08:21 UTC by MrFlashAccount

2022-06-20 13:31 UTC, tenphi requested changes

2022-06-20 13:31 UTC, tenphi commented on src/components/pickers/Select/Select.tsx
> +      '': '#white',
Sorry, it's incorrect. You can't use solid color by default and transparent on states.
You should fill the wrapper element and add `borderRadius` to it. Also, you should pass `borderRadius` to the SelectElement via `border: '@context-radius',`.

2022-06-20 13:54 UTC, MrFlashAccount commented on src/components/pickers/Select/Select.tsx
> +      '': '#white',
@tenphi, can you remind me why it's not a good solution?

2022-06-21 13:36 UTC, MrFlashAccount commented on src/components/pickers/ComboBox/ComboBox.tsx
> +    color: {
Don't forget to add story with custom bg :)

2022-06-22 11:14 UTC, tenphi approved these changes

2022-06-22 11:25 UTC, merged