fix(FileInput): add text ellipsis for long filenames
cube-js/cube-ui-kit pull request #237
Opened 2022-10-26 10:17 UTC by tenphi

2022-10-26 10:22 UTC, MrFlashAccount requested changes

2022-10-26 10:22 UTC, MrFlashAccount commented on src/components/forms/FileInput/FileInput.stories.tsx
> +    inputStyles={{ width: '300px' }}
Put this in args please.

2022-10-26 10:22 UTC, MrFlashAccount commented on src/components/forms/FileInput/FileInput.stories.tsx
> +    onChange={(query) => console.log('change', query)}
Btw, guess we should fix it.

2022-10-26 10:22 UTC, MrFlashAccount commented on src/components/forms/FileInput/FileInput.tsx
> -      // opacity: 0,
Commenting out?

2022-10-26 10:26 UTC, MrFlashAccount commented
Please add a story that tests the overflow behavior.

It's possible with testing library https://testing-library.com/docs/user-event/utility

2022-10-27 05:56 UTC, MrFlashAccount commented on src/components/forms/FileInput/FileInput.stories.tsx
> +export const LongFilePlaceholderOverflow: typeof Template = Template.bind({});
Тип можно не писать, TS умеет выводить самостоятельно :)

2022-10-27 05:56 UTC, MrFlashAccount approved these changes

2022-10-27 08:46 UTC, tenphi commented on src/components/forms/FileInput/FileInput.stories.tsx
> +export const LongFilePlaceholderOverflow: typeof Template = Template.bind({});
I had a weird typing issue and tried things :) I will remove it.

2022-10-27 11:00 UTC, merged